name: Sign Python Files and Commit Signatures

on:
  push:
    branches:
      - main

permissions:
  id-token: write  # Required for Sigstore keyless signing
  contents: write  # Required to push signature files back to the repo

jobs:
  sign:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Sigstore
        run: pip install sigstore

      - name: Sign Python Files with Sigstore
        run: |
          mkdir -p dist  # Ensure the directory exists
          sigstore sign --output-signature dist/requirements.txt.sig --output-certificate dist/requirements.txt.crt requirements.txt
          sigstore sign --output-signature dist/main.py.sig --output-certificate dist/main.py.crt src/main.py

      - name: Debug List Files in Dist Directory
        run: ls -R dist

      - name: Commit and Push Signature Files
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "github-actions@github.com"
          if ls dist/*.sig &> /dev/null; then
            git add dist/*.sig dist/*.crt
            git commit -m "Add Sigstore signatures for latest commit"
            git push origin main
          else
            echo "No signature files found, skipping commit."
          fi

